# Generated by Django 2.2.6 on 2019-10-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='영화 제목')),
                ('story', models.TextField(verbose_name='줄거리')),
                ('actors', models.CharField(max_length=100, verbose_name='주연 배우')),
                ('director', models.CharField(max_length=100, verbose_name='감독')),
                ('poster_url', models.URLField(blank=True, max_length=400, verbose_name='포스터 URL')),
                ('wordcloud', models.ImageField(blank=True, upload_to='wordclouds', verbose_name='wordcloud 이미지')),
                ('premier', models.CharField(max_length=100, verbose_name='영화 개봉일')),
                ('score', models.CharField(max_length=100, verbose_name='평점')),
            ],
            options={
                'verbose_name': '영화 데이터',
                'verbose_name_plural': '영화 데이터',
                'db_table': 'MovieData',
            },
        ),
    ]
