# Generated by Django 2.2.6 on 2019-10-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecloud', '0002_auto_20191029_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='wordcloud',
            field=models.CharField(max_length=100, verbose_name='wordcloud 이미지 경로'),
        ),
    ]
